version: 0.2
name: production

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing
  pre_build:
    commands:
      - echo Installing source NPM dependencies.

  build:
    commands:
      - ls -la
      - npm config set @apf:registry=http://35.169.115.77:4873/
      - npm install
      - npm run build
      - ls -la
      - aws s3api put-object --bucket s3://apf-hero-brik/ --key hero-brik/
      - aws s3 mv --recursive build/ s3://apf-hero-brik/hero-brik/
post_build:
  commands:
    - echo Build completed on `date`
artifacts:
  files:
    - "*/*"
